features <- tibble::tibble(
  feature = c(
    "INSGESAMT",
    "ALTER_10JG",
    "ALTER_KURZ",
    "FAMSTND_AUSF",
    "GEBURTLAND_GRP",
    "GESCHLECHT",
    "RELIGION_KURZ",
    "STAATSANGE_GRP",
    "STAATSANGE_HLND",
    "STAATSANGE_KURZ",
    "STAATZHL",
    "FAMTYP_KIND",
    "FAMGROESS_KLASS",
    "HHTYP_SENIOR_HH",
    "HHTYP_FAM",
    "HHTYP_LEB",
    "HHGROESS_KLASS",
    "NUTZUNG_DETAIL_HHGEN",
    "WOHNEIGENTUM",
    "WOHNFLAECHE_10S",
    "RAUMANZAHL",
    "GEBAEUDEART_SYS",
    "BAUJAHR_MZ",
    "EIGENTUM",
    "GEBTYPBAUWEISE",
    "GEBTYPGROESSE",
    "HEIZTYP",
    "ZAHLWOHNGN_HHG"
  ),
  feature_en = c(
    "total",
    "age_long",
    "age_short",
    "marital_status",
    "birth_country",
    "sex",
    "religion",
    "nation_group",
    "nation_country",
    "nation",
    "nation_number",
    "famtype",
    "famsize",
    "hhtype_senior",
    "hhtype_family",
    "hhtype_lifestyle",
    "hhsize",
    "dwell_use",
    "dwell_ownership",
    "dwell_space",
    "dwell_rooms",
    "build_type",
    "build_year",
    "build_ownership",
    "build_construction",
    "build_size",
    "build_heating",
    "build_dwellings"
  ),
  german = c(
    "Gesamtzahl der Einheiten in der Gitterzelle",
    "Alter (10er-Jahresgruppen)",
    "Alter (5 Altersklassen)",
    "Familienstand",
    "Geburtsland (Gruppen)",
    "Geschlecht",
    "Religion",
    "Staatsangehörigkeitsgruppen",
    "Staatsangehörigkeit nach ausgewählten Ländern",
    "Staatsangehörigkeit",
    "Zahl der Staatsangehörigkeiten",
    "Typ der Kernfamilie (nach Kindern)",
    "Gr\u00f6\u00dfe der Kernfamilie",
    "Seniorenstatus eines privaten Haushalts",
    "Typ des privaten Haushalts (nach Familien)",
    "Typ des privaten Haushalts (nach Lebensform)",
    "Größe des privaten Haushalts",
    "Nutzung nach Belegung durch Haushalt",
    "Eigentumsverhältnisse der Wohnung",
    "Fläche der Wohnung (10m\u00b2 Intervalle)",
    "Zahl der Räume",
    "Art des Gebäudes",
    "Baujahr",
    "Eigentumsform des Gebäudes",
    "Gebäudetyp-Bauweise",
    "Gebäudetyp-Größe",
    "Heizungsart",
    "Zahl der Wohnungen im Gebäude"
  ),
  english = c(
    "Total number of units per cell",
    "Age (year groups of 10)",
    "Age (5 age groups)",
    "Marital status",
    "Country of birth (groups)",
    "Sex",
    "Religion",
    "Nationality groups",
    "Nationality by selected countries",
    "Nationality",
    "Number of nationalities",
    "Type of the core family (by children)",
    "Size of the core family",
    "Senior status of a private household",
    "Type of the private household (by family)",
    "Type of the private household (by lifestyle)",
    "Size of the private household",
    "Use by household occupancy",
    "Ownership of the dwelling",
    "Area of the dwelling (10m\u00b2 intervals)",
    "Number of rooms",
    "Type of building",
    "Year of construction (microcensus classes)",
    "Type of ownership of the building",
    "Type of building - construction",
    "Type of building - size",
    "Heating type",
    "Number of dwellings in the building"
  )
)

usethis::use_data(features, overwrite = TRUE, compress = FALSE)
